redis:
  uri: http://localhost:6379/
aws:
  access_key_id: OVERRIDE_ME
  secret_access_key: OVERRIDE_ME
hasher:
  secret_key: OVERRIDE_ME
google_analytics:
  analytics_id: UA-31572927-1
email:
  from_address: Do Not Reply <admin@demandprogress.org>
  domain: demandprogress.org
action_kit:
   host: <%= ENV["AK_IMPORT_DB_HOST"] %>
   username: <%= ENV["AK_IMPORT_DB_UNAME"] %>
   password: <%= ENV["AK_IMPORT_DB_PWD"] %>
   database: <%= ENV["AK_IMPORT_DB"] %>
cloudmailin:
  token: <%= ENV["CLOUDMAILIN_TOKEN"] %>
organization:
  name: "Demand Progress"
  email: "info@demandprogress.org"
  unsubscribe_url: "https://act.demandprogress.org/unsubscribe/unsubscribe?source=victorykit"
  logo: 'logo.png'
site:
  name: "DemandProgress.org"
  email: "support@demandprogress.org"
  hostname: "act.demandprogress.org"
  feedback_email: info+victorykit@demandprogress.org
  list_unsubscribe: "unsubscribe@appmail.demandprogress.org"
